---
  - name: Prompt for username
    pause: prompt="Enter the username"
    register: username

  - name: Prompt for password
    pause:
        prompt: "Enter the password"
        echo: no
    register: password

  - name: Prompt for role
    pause: prompt="Enter the group assigned to the user?"
    register: role

  - debug: var=role

  - debug: var=password

  - set_fact:
      uname: "{{username.user_input}}"
      assigned_group: "{{role.user_input}}"

  - name: Printing the username
    debug:
      msg={{uname}}

  - name : Store the password in a variable
    command: echo "{{password.user_input | password_hash('sha512')}}"
    register: upassword

  - name: Creating the user with "{{username.user_input}}"
    user: name={{uname}} password={{upassword.stdout}} group="{{assigned_group}}"
          append=yes shell=/bin/bash
    when: (assigned_group|lower == 'no')

  - name: Creating home directory for {{uname}}
    file: path=/home/{{uname}} state=directory owner={{uname}} group={{assigned_group}} mode=0755

  - name: Modify the home directory for the {{username.user_input}}
    user:
      name: "{{username.user_input}}"
      home: "/home/{{username.user_input}}"

  - name: Add a line in acces.conf for user {{uname}}
    lineinfile:
      path: /etc/security/access.conf
      insertbefore: '^- : ALL : ALL'
      line: '+ : {{uname}} : ALL'
