---
  - name: Prompt for username
    pause: prompt="Enter the username"
    register: username

  - name: Prompt for password
    pause:
        prompt: "Enter the password"
        echo: no
    register: password

  - name: Prompt for role
    pause: prompt="Do you want to create the user with admin access (y/n) ?"
    register: role

  - debug: var=role

  - debug: var=password

  - set_fact:
      uname: "{{username.user_input}}"

  - name : Store the password in a variable
    command: echo "{{password.user_input | password_hash('sha512')}}"
    register: upassword

  - name: Creating the user with "{{username.user_input}}"
    user: name={{username.user_input}} password={{upassword.stdout}} group=ssh
          append=yes shell=/bin/bash
    when: (role|lower == 'no')

  - name: Creating home directory for {{uname}}
    file:
      path: "/home/{{username.user_input}}"
      state: directory
      owner: "{{uname}}"
      group: "{{uname}}"
      mode: '0755'

  - name: Add a line in acces.conf for user {{uname}}
    lineinfile: path=/etc/security/access.conf
    insertbefore: '^- : ALL : ALL'
    line: '+ : {{uname}} : ALL'
