-
  name: Test connectivity with the target system
  hosts: webserver
  #vars_prompt:
    #- name: username
      #prompt: "Enter the username {{zone}}"
      #private: no

  tasks:

    - name: Priting the value
      debug:
        msg="{{ce_app_user}}"

    - name: Printing the properties
      debug:
        var: ce_app_user

    #- name: Printing the properties
      #debug:
        #var: webserver-host

    - name: Generate a password
      pause: prompt="Enter a password"
      register: password

    #- name: Create User
    #  user: name="ceuat1" group="ssh"

    - name: Saving the user password
      set_fact: upassword="{{password.user_input}}"

    - name: printing password in encoded format
      debug:
        msg="{{upassword | password_hash('sha512')}}"
