-
  name: Test connectivity with the target system
  hosts: webserver
  tasks:

    - name: Generate a password
      pause: prompt="Enter a password"
      register: password

    #- name: Create User
    #  user: name="ceuat1" group="ssh"

    - name: Saving the user password
      set_fact: upassword="{{password.user_input}}"

    - name: printing password in encoded format
      debug:
        msg="{{upassword | password_hash('sha512')}}"
