-
  name: Test connectivity with the target system
  hosts: webserver
  vars_prompt:
    - name: "password"
      prompt: "Enter the password"
      private: yes
      #encrypt: "sha512_crypt"
      confirm: yes

  tasks:

    - name: Printing the password
      debug:
        var: password

    - name : Store the password in a variable
      command: echo "{{password | password_hash('sha512')}}"
      register: upassword

    - debug: var=upassword.stdout

    #- name: Priting the application username
    #  debug:
    #    msg="{{ce_app_user}}"

############################## PAUSE MODULE #############################################################
    #- name: Generate a password
    #  pause: prompt="Enter a password"
    #  register: password

############################# USER MODULE ##############################################################
    - name: Create User
      user: name="ceuat10" group="ssh"
