-
  name: Test connectivity with the target system
  hosts: webserver
  tasks:

    - name: Generate a password
      pause: prompt="Enter a password"
      register: password

    #- name: Create User
    #  user: name="ceuat1" group="ssh"

    - name: Printing the password
      debug: var=password
