-
  name: Setting up the load balancer layer
  hosts: control
  tasks:

    - name: Install dependencies for the ansible host machine
      apt: name={{item}} state=present update_cache=yes
      become: true
      with_items:
        - curl
