-
  name: Setting up the load balancer layer
  hosts: databases
  tasks:

    - name: Install dependencies for the databases
      apt: name={{item}} state=present update_cache=yes
      become: true
      with_items:
        - mysql-server

    - name: Ensure mysql-server is running on my target machine
      service: name=mysql state=started enabled=yes
