-
  name: Setting up the load balancer layer
  hosts: eastzone
  tasks:

    - name: Install dependencies for the databases
      apt: name={{item}} state=present update_cache=yes
      become: true
      with_items:
        - mysql-server
