-
  name: Setting up the load balancer layer
  hosts: databases
  tasks:

    - name: Install dependencies for the databases
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - mysql-server

    - name: Ensure mysql-server is running on my target machine
      service: name=mysql state=started enabled=yes

    - name: Do something and then restart the mysql service
      command : echo $HOME

  handlers:
    - name: Restart mysql
      service: name=mysql state=started enabled=yes
