-
  name: Setting up the load balancer layer
  hosts: eastzone
  tasks:

    - name: Install Dependencies for the loadbalancer
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - nginx
