-
  name: Read a token using regular expression
  hosts: webserver

  tasks:
    - name: Ensure a configuration directory exists in $HOME/app
      file:
        path: /home/LDC/app/conf
        state: directory

    #- name: Copy token file to the target system
    #  copy:
    #    src: /home/LDC/ansible-inventory-check/conf/token.properties
    #    dest: /home/LDC/app/conf/{{file}}

    - name: Ansible date timestamp example
      debug:
        var: ansible_date_time.time

    - debug: msg="{{ lookup('pipe','date') }}"

    - name: Loop through the tasks
      include_tasks: read-replace-app-token.yaml
      with_items: "{{ lookup('file', '/home/LDC/ansible-inventory-check/conf/input.txt').splitlines() }}"
        #- {file: app-conf1, ext: xml}
        #- {file: app-conf2, ext: xml}
        #- {file: app-conf3, ext: xml}
        #- {file: app-conf4, ext: xml}
        #- {file: app-conf5, ext: xml}
        #- {file: app-conf6, ext: xml}
        #- {file: app-conf7, ext: xml}
        #- {file: app-conf8, ext: xml}
        #- {file: app-conf9, ext: xml}
        #- {file: app-conf10, ext: xml}
        #- {file: purchaseOrder, ext: xml}
        #- {file: token, ext: properties}
      loop_control:
        loop_var: file

    - name: Ansible date timestamp example
      debug:
          var: ansible_date_time.time

    - debug: msg="{{ lookup('pipe','date') }}"

