-
  name: Deploy Calculate Engine in the single box
  hosts: webserver
  tasks:
    #- name: Install tools
    #  apt: name={{item}} state=present update_cache=yes
    #  with_items:
    #    - python-lxml

    - name: Ensure a configuration directory exists in $HOME/app
      file:
        path: $HOME/app/conf
        state: directory

    - name: Copy application configuration files
      copy:
        src:  purchaseOrder.xml
        dest: $HOME/app/conf/purchaseOrder.xml

    - name: Read the application-configuration.xml
      xml:
        path: $HOME/app/conf/purchaseOrder.xml
        xpath: /PurchaseOrders/PurchaseOrder/Items/Item
        content: text
      register: hits
    - debug:
        var: hits

    - name: Read application configuration xml file to parse the list of other configuration, sql and scripting files
      xml:
        path: $HOME/app/conf/purchaseOrder.xml
        xpath: /PurchaseOrders/PurchaseOrder/Items/Item
        content: attribute
        attribute: PartNumber
      register: xmlresp

    #- debug:
    #    var : xmlresp

    #- name: Storing the content of the file
    #  set_fact:
    #    fileNameList: "{{xmlresp.matches}}"

    #- name: Record Files to look up for the tokens
    #  debug: var=xmlresp.matches[{{ item }}].Item.PartNumber
    #  with_sequence: start=0 end={{xmlresp.matches | length -1}}

    #- name: List out all other configuration in configFiles.txt
    #  copy:
    #    dest: $HOME/app/conf/configFiles.txt
        #content: "Jai Ganesh Ji Maharaj Ki Jai"
    #    content: "{{item.Item.PartNumber}}"
    #  loop: "{{xmlresp.matches}}"


    #- name: Create a file which contain list of all the parsed files
    #  file:
    #    path: /home/LDC/app/conf/input.txt
    #    state: touch

    #- name: Write down the list of files to be read for tokens
    #  lineinfile: path=/home/LDC/app/conf/input.txt line={{item.Item.PartNumber}} create=yes state=present create=yes
    #  loop: "{{xmlresp.matches}}"

    - name: create a file to store the list of configuration files
      shell: cat > /home/LDC/app/conf/input.txt

    - name: Write down the list of files to be read for tokens
      shell: echo '{{item.Item.PartNumber}}' >> /home/LDC/app/conf/input.txt
      loop: "{{xmlresp.matches}}"

