-
  name: Create a directory app-conf in the $HOME/app/conf directory
  hosts: webserver
  tasks:
    - name: Ensure a configuration directory exists in $HOME/app
      file:
        path: $HOME/app/conf
        state: directory

    - name: create multiple directory in the $HOME
      file:
        path: "$HOME/{{item}}"
        state: directory
      loop:
        - app/conf
        - app/source
        - app/meta-inf