-
  name: Create a directory app-conf in the $HOME/app/conf directory
  hosts: webserver
  tasks:
    - name: Install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - python-lxml
    - name: Ensure a configuration directory exists in $HOME/app
      file:
        path: $HOME/app/conf
        state: directory

    - name: create multiple directory in the $HOME
      file:
        path: "$HOME/{{item}}"
        state: directory
      loop:
        - app/conf
        - app/source
        - app/meta-inf

    - name : remove multiple directories created in the step above
      file:
        path: "$HOME/{{item}}"
        state: absent
      loop:
        - app/source
        - app/meta-inf

    - name: Copy File
      copy:
        src:  purchaseOrder.xml
        dest: $HOME/app/conf/purchaseOrder.xml

    - name: Read the xml file
      xml:
        path: $HOME/app/conf/purchaseOrder.xml
        xpath: /PurchaseOrders/PurchaseOrder/Items/Item
        content: text
      register: hits
    - debug:
        var: hits

    - name: Read the xml file for the Items
      xml:
        path: $HOME/app/conf/purchaseOrder.xml
        xpath: /PurchaseOrders/PurchaseOrder/Items/Item
        content: attribute
        attribute: PartNumber
      register: xmlresp

    - debug:
        var : xmlresp



    - copy:
        dest: $HOME/app/conf/configFiles.txt
        content: "| {{item.Item.PartNumber}}"
        with_subelements: "{{xmlresp.matches}}"




