-
  name: Create a directory app-conf in the $HOME/app/conf directory
  hosts: webserver
  tasks:
    - name: Ensure a configuration directory exists in $HOME/app
      file:
        path: $HOME/app/conf
        state: directory

    - name: create multiple directory in the $HOME
      file:
        path: "$HOME/{{item}}"
        state: directory
      loop:
        - app/conf
        - app/source
        - app/meta-inf

    - name : remove multiple directories created in the step above
      file:
        path: "$HOME/{{item}}"
        state: absent
      loop:
        - app/source
        - app/meta-inf


    - name: Read the xml file
      xml:
        path: /ansible-inventory-check/playbooks/purchaseOrder.xml
        xpath: /PurchaseOrders/PurchaseOrder/Items/Item
        count: yes
        register: xmlresp

    - name: print the xml resp
      debug: var=xmlresp