
    - name: Copy application configuration files to the target system
      copy:
        src: /home/LDC/ansible-inventory-check/conf/{{file}}
        dest: /home/LDC/app/conf/{{file}}

    - name: Reading the file contents on the target machines to a variable
      slurp:
        src: /home/LDC/app/conf/{{file}}
      register: fileContent

    - name: Decoding the content from base 64 to normal text
      set_fact:
        fileString: "{{ fileContent.content | b64decode }}"

    - name: Print the file content on the screen
      debug:
        var: fileString

    - name: Find the tokens (@----@) in the fileString
      set_fact:
        tokenObject: "{{ fileString | regex_findall(regexp)}}"
      vars:
        regexp: '(?<=\@)(.*?)(?=\@)'

    - name: Print Token Objects
      debug:
        var: tokenObject

    #- debug:
    #    msg="{{ lookup('ini', '{{item}} type=properties file=/home/LDC/ansible-inventory-check/conf/token.properties') }}"
    #  loop: "{{tokenObject}}"
    #  register: myresult

    #- debug:
    #    var : myresult

    - set_fact:
        fileTokens : "{{tokenObject}}"

    - name: Replace the token in the configuration files
      replace:
        path: /home/LDC/app/conf/{{file}}
        regexp: '{{tokens}}'
        #replace: 'GaneshJi'
        replace: "{{ lookup('ini', '{{tokens}} type=properties file=/home/LDC/ansible-inventory-check/conf/token.properties') }}"
      with_items: "{{fileTokens}}"
      loop_control:
        loop_var: tokens


