-
  name: Read a file from the system
  hosts: webserver
  tasks:
    - name: Copy File
        copy:
        src: /ansible-inventory-check/playbooks/purchaseOrder.xml
        dest: $HOME/app/conf/purchaseOrder.xml

    - name: display multiple file contents
      debug: var=item
      with_file:
        - "/root/ansible-inventory-check/playbooks/purchaseOrder.xml"

    - name: Look up for a file and read it
        var: fileContent={{lookup('file', '/root/ansible-inventory-check/playbooks/purchaseOrder.xml') }}