-
  name: Read a file on the target system
  hosts: webserver
  tasks:
    - name: Copy File to the target system
      copy:
        src: /ansible-inventory-check/playbooks/purchaseOrder.xml
        dest: $HOME/app/conf/purchaseOrder.xml

    - name: importing the file contents to variable
      slurp:
        src: $HOME/app/conf/purchaseOrder.xml
      register: idb_endpoint_b64



    - debug:
        var: idb_endpoint_b64.content

