-
  name: Read a file from the system
  hosts: webserver
  tasks:
    - name: Copy File
      copy:
        src: /ansible-inventory-check/playbooks/purchaseOrder.xml
        dest: $HOME/app/conf/purchaseOrder.xml

    - name: importing the file contents to variable
      slurp:
        src: $HOME/app/conf/purchaseOrder.xml
      register: idb_endpoint_b64

    - set_fact:
        idb_endpoint: "{{ idb_endpoint_b64.content}}"

    - debug:
        var: idb_endpoint

