-
  name: Read a token using regular expression
  hosts: webserver
  tasks:
    - name: Ensure a configuration directory exists in $HOME/app
      file:
        path: /home/LDC/app/conf
        state: directory
    - name: Copy configuration xml files to the target system
      copy:
        src: /home/LDC/ansible-inventory-check/conf/{{item.file}}.{{item.ext}}
        dest: /home/LDC/app/conf/{{item.file}}.{{item.ext}}
      loop:
        - {file: app-conf1, ext: xml}
        - {file: app-conf2, ext: xml}
        - {file: purchaseOrder, ext: xml}
        - {file: token, ext: properties}

    - name: importing the file contents to variable
      slurp:
        src: /home/LDC/app/conf/purchaseOrder.xml
      register: idb_endpoint_b64

    - name: Decoding the content from base 64 to normal text
      set_fact:
        idb_endpoint: "{{ idb_endpoint_b64.content | b64decode }}"

    - name: Print the content on the screen
      debug:
        var: idb_endpoint

    - shell: echo 'vault-option name="@KEYSTORE_PASSWORD@" value="@MASK-5dOaAVafCSd@" value="@One more time@" value="@MASK-ED-123-LT@"'
      register: results

    - debug:
        var: results

    - set_fact:
        myvalue: "{{ idb_endpoint | regex_findall(regexp)}}"
      vars:
        regexp: '(?<=\@)(.*?)(?=\@)'

    - debug:
        var: myvalue

    - debug:
        msg="{{ lookup('ini', '{{item}} type=properties file=/home/LDC/ansible-inventory-check/conf/token.properties') }}"
      loop: "{{myvalue}}"
      register: myresult

    - debug:
        var : myresult

    - set_fact:
        resultingToken: "{{myresult.results}}"

    - debug:
        var: resultingToken


    - template:
        src: /home/LDC/ansible-inventory-check/conf/PO.j2
        dest: /home/LDC/app/conf/PO.xml
      loop: "{{myresult}}"


    - name: Replace the token in the configuration files
      replace:
        path: /home/LDC/app/conf/purchaseOrder.xml
        regexp: '{{item.item}}'
        #replace: 'GaneshJi'
        replace: "{{ lookup('ini', '{{item.item}} type=properties file=/home/LDC/ansible-inventory-check/conf/token.properties') }}"
      with_items: "{{resultingToken}}"


