-
  name: Create a directory app-conf in the $HOME/app/conf directory
  hosts: webserver.yaml
  tasks:
    - name: Ensure a configuration directory exists in $HOME/app
      file:
        path: $HOME/app/conf
        state: directory

    - name: create multiple directory in the $HOME
      file:
        path: "$HOME/{{item}}"
        state: directory
      loop:
        - app/conf
        - app/source
        - app/meta-inf

    - name : remove multiple directories created in the step above
      file:
        path: "$HOME/{{item}}"
        state: absent
      loop:
        - app/source
        - app/meta-inf

    - name: Copy File
      copy:
        src: "/home/LDC/ansible-inventory-check/conf/{{item}}.xml"
        dest: "/home/LDC/app/conf/{{item}}.xml"
      loop:
        - app-conf1
        - app-conf2
        - purchaseOrder

    - name: Replace the token in the configuration files
      replace:
        path: "{{item.path}}"
        regexp: "{{item.regex}}"
        replace: "{{item.replace}}"
      with_items:
        - {path: '/home/LDC/app/conf/app-conf1.xml', regex: '(?<=\@)(.*?)(?=\@)', replace: 'GaneshJi'}
        - {path: '/home/LDC/app/conf/app-conf2.xml', regex: '(?<=\@)(.*?)(?=\@)', replace: 'GaneshJiBhagwan'}
        - {path: '/home/LDC/app/conf/purchaseOrder.xml', regex: '(?<=\@)(.*?)(?=\@)', replace: 'GaneshJiBhagwan'}

    #- name: Read the token in the configuration file
    #  set_fact:
    #  myvalue: "{{ results.stdout | regex_search(regexp,'\\1') }}"